routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('guest')->group(function() {
    Route::redirect('/', 'login');
    Route::view('/login', 'auth.login')->name('login');
    Route::view('/register', 'auth.register')->name('register');
    Route::post('/login', [Controllers\AuthController::class, 'login'])->name('login.post');
    Route::post('/register', [Controllers\AuthController::class, 'register'])->name('register.post');
});

Route::middleware('auth')->group(function() {
    Route::get('/home', [Controllers\DashboardController::class, 'index'])->name('home');
    Route::any('/logout', [Controllers\AuthController::class, 'logout'])->name('logout');

    // User
    Route::get("/user-profile", [Controllers\UserController::class, 'profile'])->name('profile');
    Route::post("/update-avatar", [Controllers\UserController::class, 'update_avatar'])->name('update.avatar');
    Route::post("/update-profile", [Controllers\UserController::class, 'update_profile'])->name('update.profile');
    Route::post("/update-password", [Controllers\UserController::class, 'update_password'])->name('update.password');
    Route::get("/users", [Controllers\UserController::class, 'index'])->name('users.index');

    Route::resources([
        "sales" => Controllers\SaleController::class,
        "inventory" => Controllers\InventoryController::class,
        "customers" => Controllers\CustomerController::class,
        "articles" => Controllers\ArticleController::class,
        "categories" => Controllers\CategoryController::class,
        "suppliers" => Controllers\SupplierController::class,
        "paymentModes" => Controllers\PaymentModeController::class,
        "conditionings" => Controllers\ConditioningController::class,
        "customereWallets" => Controllers\CustomereWalletController::class,
    ]);
});


// Commands
Route::get("/fitz/migrate", function () {
    try {
        \Illuminate\Support\Facades\Artisan::call("migrate");
    } catch(\Exception $e) {
        dd($e->getMessage());
    }
});
Route::get("/fitz/clear", function () {
    try {
        \Illuminate\Support\Facades\Artisan::call("route:clear");
        \Illuminate\Support\Facades\Artisan::call("cache:clear");
        \Illuminate\Support\Facades\Artisan::call("config:clear");
        \Illuminate\Support\Facades\Artisan::call("view:clear");

        return "route, cache, config and view cleared";
    } catch(\Exception $e) {
        dd($e->getMessage());
    }
});
Route::get("/fitz/seed", function () {
    try {
        \Illuminate\Support\Facades\Artisan::call("db:seed");
    } catch(\Exception $e) {
        dd($e->getMessage());
    }
});

resources/views/includes/sidebar.blade.php
<div class="sidebar-wrapper" data-simplebar="true">
    <div class="sidebar-header">
        <div>
            <img src="{{asset('logo.jpg')}}" class="logo-icon" alt="logo icon">
        </div>
        <div>
            {{--
                        <h4 class="logo-text">Probat</h4>
            --}}
        </div>
        <div class="toggle-icon ms-auto"><i class='bx bx-arrow-to-left'></i>
        </div>
    </div>
    <!--navigation-->
    <ul class="metismenu" id="menu">
        <li>
            <a href="{{ route('home') }}">
                <div class="parent-icon"><i class='bx bx-pie-chart-alt-2'></i>
                </div>
                <div class="menu-title">Tableau de board</div>
            </a>
        </li>

        <li class="menu-label">Gestion stocks</li>
        <li>
            <a href="javascript:;" class="has-arrow">
                <div class="parent-icon"><i class='bx bx-money'></i>
                </div>
                <div class="menu-title">Ventes</div>
            </a>
            <ul>
                <li>
                    <a href="{{ route('sales.create',) }}"><i class="bx bx-right-arrow-alt"></i>Vendre</a>
                </li>
                <li>
                    <a href="{{ route('sales.index') }}"><i class="bx bx-right-arrow-alt"></i>Listes des ventes</a>
                </li>
            </ul>
        </li>

        <li>
            <a href="javascript:;" class="has-arrow">
                <div class="parent-icon"><i class='bx bx-package'></i>
                </div>
                <div class="menu-title">Inventaire</div>
            </a>
            <ul>
                <li>
                    <a href="{{ route('articles.index') }}"><i class="bx bx-right-arrow-alt"></i>Articles</a>
                </li>
            </ul>
        </li>

        <li>
            <a href="javascript:;" class="has-arrow">
                <div class="parent-icon"><i class='bx bx-store-alt'></i>
                </div>
                <div class="menu-title">Fournisseurs</div>
            </a>
            <ul>
                <li>
                    <a href="{{ route('suppliers.index') }}"><i class="bx bx-right-arrow-alt"></i>Liste des Fournisseurs</a>
                </li>
            </ul>
        </li>

{{--        <li class="menu-label">Tresorerie</li>
        <li>
            <a href="javascript:;" class="has-arrow">
                <div class="parent-icon"><i class='bx bxs-bank'></i>
                </div>
                <div class="menu-title">Banque</div>
            </a>
            <ul>
                <li>
                    <a href="#"><i class="bx bx-right-arrow-alt"></i>Vendre</a>
                </li>
                <li>
                    <a href="#"><i class="bx bx-right-arrow-alt"></i>Listes des ventes</a>
                </li>
            </ul>
        </li>--}}

        <li class="menu-label">Gestion clients</li>
        <li>
            <a href="javascript:;" class="has-arrow">
                <div class="parent-icon"><i class='bx bx-group'></i>
                </div>
                <div class="menu-title">Compte clients</div>
            </a>
            <ul>
                <li>
                    <a href="{{ route('customereWallets.create') }}"><i class="bx bx-right-arrow-alt"></i>Ajouter
                        Portefeuille client</a>
                </li>
                <li>
                    <a href="{{ route('customers.create') }}"><i class="bx bx-right-arrow-alt"></i>Nouveau client</a>
                </li>
                <li>
                    <a href="{{ route('customers.index') }}"><i class="bx bx-right-arrow-alt"></i>Liste client(s)</a>
                </li>
            </ul>
        </li>

        <li class="menu-label">Paramètres</li>

        <li>
            <a href="{{ route('categories.index') }}">
                <div class="parent-icon">
                    <i class='bx bxs-grid-alt'></i>
                </div>
                <div class="menu-title">Categories</div>
            </a>
        </li>

        <li>
            <a href="{{ route('conditionings.index') }}">
                <div class="parent-icon">
                    <i class='bx bxs-package'></i>
                </div>
                <div class="menu-title">Conditionements</div>
            </a>
        </li>

        <li>
            <a href="{{ route('paymentModes.index') }}">
                <div class="parent-icon">
                    <i class='bx bx-money'></i>
                </div>
                <div class="menu-title">Modes de paiement</div>
            </a>
        </li>

        <li class="menu-label"> Gestion utilisateurs</li>

        <li>
            <a href="javascript:;" class="has-arrow">
                <div class="parent-icon"><i class='bx bxs-user-detail'></i>
                </div>
                <div class="menu-title">Users</div>
            </a>
            <ul>
                {{--<li>
                    <a href="#"><i class="bx bx-right-arrow-alt"></i>Créer un User</a>
                </li>--}}
                <li>
                    <a href="{{ route('users.index') }}"><i class="bx bx-right-arrow-alt"></i>Liste des Users</a>
                </li>
            </ul>
        </li>
        {{--        <li class="menu-label">Configuration</li>--}}
        {{--        <li>--}}
        {{--            <a href="javascript:;" class="has-arrow">--}}
        {{--                <div class="parent-icon"><i class='bx bx-user-check'></i>--}}
        {{--                </div>--}}
        {{--                <div class="menu-title">Rôles</div>--}}
        {{--            </a>--}}
        {{--            <ul>--}}
        {{--                <li>--}}
        {{--                    <a href="#"><i class="bx bx-right-arrow-alt"></i>Créer un rôle</a>--}}
        {{--                </li>--}}
        {{--                <li>--}}
        {{--                    <a href="#"><i class="bx bx-right-arrow-alt"></i>Liste des rôles</a>--}}
        {{--                </li>--}}
        {{--            </ul>--}}
        {{--        </li>--}}
        {{--        <li>--}}
        {{--            <a href="javascript:;" class="has-arrow">--}}
        {{--                <div class="parent-icon"><i class='bx bx-user-x'></i>--}}
        {{--                </div>--}}
        {{--                <div class="menu-title">Permissions</div>--}}
        {{--            </a>--}}
        {{--            <ul>--}}
        {{--                <li>--}}
        {{--                    <a href="#"><i class="bx bx-right-arrow-alt"></i>Créer une permission</a>--}}
        {{--                </li>--}}
        {{--                <li>--}}
        {{--                    <a href="#"><i class="bx bx-right-arrow-alt"></i>Liste des permissions</a>--}}
        {{--                </li>--}}
        {{--            </ul>--}}
        {{--        </li>--}}
    </ul>
    <!--end navigation-->
</div>